const SUBJECTS=[
{id:"bm",file:"bahasa-melayu.json",name:"Bahasa Melayu",icon:"📖",desc:"Membaca, menulis, bertutur dan memahami bahasa.",cls:"pink"},
{id:"english",file:"english-superminds.json",name:"English Year 1",icon:"🇬🇧",desc:"Learn English through simple, fun activities.",cls:"blue"},
{id:"math",file:"matematik.json",name:"Matematik",icon:"🔢",desc:"Nombor, operasi, bentuk dan penyelesaian masalah.",cls:"green"},
{id:"science",file:"sains.json",name:"Sains",icon:"🔬",desc:"Meneroka dunia dengan kemahiran saintifik.",cls:"orange"}];
const key="ticerAinaaEduQuestV4";
const avatars=["🧒","👧","🧑‍🎓","👦","👩‍🎓","🧒🏻","👧🏻","🧑🏻‍🏫","🦸","🧙","🦄","🐼"];
const defaultState={xp:0,stars:0,badges:[],completed:[],quizzes:0,best:0,name:"Murid",avatar:"🧒",streak:0,lastDate:"",quizHistory:[],gameWins:0};
function state(){try{return {...defaultState,...JSON.parse(localStorage.getItem(key)||"{}")} }catch(e){return {...defaultState}}}
function save(s){localStorage.setItem(key,JSON.stringify(s))}
function level(xp){return Math.floor(xp/100)+1}
function levelProgress(xp){return xp%100}
function today(){return new Date().toISOString().slice(0,10)}
function updateStreak(st){let t=today();if(st.lastDate===t)return;let y=new Date();y.setDate(y.getDate()-1);let prev=y.toISOString().slice(0,10);st.streak=st.lastDate===prev?st.streak+1:1;st.lastDate=t}
function speak(text,lang){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang=lang||'ms-MY';u.rate=.85;window.speechSynthesis.speak(u)}
function renderProfile(){let s=state(),n=document.getElementById("studentName");if(n)n.value=s.name==="Murid"?"":s.name;let h=document.getElementById("hello");if(h)h.textContent=s.name;let a=document.getElementById("avatarBig");if(a)a.textContent=s.avatar;let g=document.getElementById("avatarGrid");if(g)g.innerHTML=avatars.map(a=>`<button type="button" aria-label="Avatar ${a}" class="avatar-choice ${a===s.avatar?'selected':''}" onclick="selectAvatar('${a}')">${a}</button>`).join("")}
function selectAvatar(a){let s=state();s.avatar=a;save(s);renderProfile()}
function saveProfile(){let s=state();s.name=(document.getElementById("studentName").value.trim()||"Murid").slice(0,30);save(s);let m=document.getElementById("profileMsg");if(m)m.textContent="✅ Profil berjaya disimpan!";let h=document.getElementById("hello");if(h)h.textContent=s.name;updateHomeStats()}
async function getSubject(id){let x=SUBJECTS.find(a=>a.id===id);if(!x)throw new Error("Subjek tidak ditemui");const res=await fetch(x.file+"?v=60",{cache:"no-store"});if(!res.ok)throw new Error("Gagal memuat "+x.file);return await res.json()}
function renderSubjects(id){let el=document.getElementById(id);if(!el)return;el.innerHTML=SUBJECTS.map(s=>`<article class="card subject-card"><div class="subject-art">${s.icon}<span>${s.id==='english'?'ABC':'★'}</span></div><h3>${s.name}</h3><p>${s.desc}</p><div class="card-actions"><a class="btn primary" href="lesson.html?subject=${s.id}">Buka subjek →</a><button class="icon-btn" onclick="speak('${s.name}','ms-MY')" title="Dengar nama subjek">🔊</button></div></article>`).join("")}
function updateHomeStats(){let s=state();for(let k of ["stars","xp","badges"]){let el=document.getElementById(k);if(el)el.textContent=k==="badges"?s.badges.length:s[k]}let n=document.getElementById("studentWelcome");if(n)n.textContent=s.name;let av=document.getElementById("homeAvatar");if(av)av.textContent=s.avatar;let lv=document.getElementById("homeLevel");if(lv)lv.textContent=`Level ${level(s.xp)}`;let lp=document.getElementById("homeLevelBar");if(lp)lp.style.width=levelProgress(s.xp)+"%"}
function visualFor(id){return {bm:"🗣️📚",english:"🔤🗣️",math:"🔢🧮",science:"🔬🌱"}[id]||"🌟"}
async function renderLesson(){let p=new URLSearchParams(location.search),id=p.get("subject")||"bm",data=await getSubject(id);document.title=data.name+" - TicerAinaaEdu Quest";let root=document.getElementById("lesson");if(!root)return;root.innerHTML=`<div class="subject-banner"><div class="big-visual">${visualFor(id)}</div><div><p class="eyebrow">${data.icon} ${data.name}</p><h1>Pilih unit</h1><p>${data.desc}</p><button class="btn" onclick="speak('${data.name}','ms-MY')">🔊 Dengar subjek</button></div></div><div class="grid">${data.units.map((u,i)=>`<article class="card unit"><div class="unit-top"><div class="num">${i+1}</div><div class="unit-emoji">${id==='math'?'🔢':id==='science'?'🔬':id==='english'?'🔤':'📖'}</div></div><div><h3>${u.title}</h3><p>${u.learn}</p><ul class="points">${(u.points||[]).map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="card-actions"><a class="btn primary" href="quiz.html?subject=${id}&unit=${i}">Mula kuiz →</a><button class="icon-btn" onclick="speak('${String(u.title).replace(/'/g,"\\'")}','ms-MY')">🔊</button></div></article>`).join("")}</div>`}
function adaptiveMessage(score,total){let pct=Math.round(score/total*100);if(pct<50)return "🌱 Jom cuba lagi dengan latihan sokongan. Sedikit demi sedikit, pasti boleh!";if(pct<80)return "🚀 Bagus! Cuba sekali lagi untuk tingkatkan skor.";return "🌟 Hebat! Awak bersedia untuk cabaran seterusnya."}
async function renderQuiz(){let p=new URLSearchParams(location.search),id=p.get("subject")||"bm",ui=Number(p.get("unit")||0),data=await getSubject(id),u=data.units[ui];if(!u){location.href="subjects.html";return}let root=document.getElementById("quiz"),score=0,answered=0;let old=state().quizHistory.find(x=>x.unitId===u.id);root.innerHTML=`<div class="quiz-head"><div><p class="eyebrow">${data.icon} ${data.name}</p><h1>${u.title}</h1></div><div class="mode-pill">🧠 Kuiz Pintar</div></div><div class="lesson-box"><div class="lesson-visual">${visualFor(id)}</div><div><h3>💡 Apa kita belajar?</h3><p>${u.learn}</p><p><b>🎯 Aktiviti:</b> ${u.activity}</p><button class="btn" onclick="speak('${String(u.learn).replace(/'/g,"\\'")}','ms-MY')">🔊 Dengar penerangan</button></div></div><div class="adaptive-note">${old?`🧠 Cubaan sebelum ini: <b>${old.percent}%</b>. ${adaptiveMessage(Math.round(old.percent*u.quiz.length/100),u.quiz.length)}`:`🧠 Kuiz Pintar akan beri maklum balas berdasarkan prestasi awak.`}</div><div id="questions"></div><div id="result"></div>`;
let qbox=document.getElementById("questions");u.quiz.forEach((q,qi)=>{let [text,opts,ans]=q,d=document.createElement("div");d.className="quiz-q";d.innerHTML=`<div class="question-title"><h3>${qi+1}. ${text}</h3><button class="icon-btn" onclick="speak('${String(text).replace(/'/g,"\\'")}','ms-MY')">🔊</button></div>`+opts.map((o,i)=>`<button class="option" data-i="${i}">${o}</button>`).join("");qbox.appendChild(d);d.querySelectorAll(".option").forEach(b=>b.onclick=()=>{if(d.dataset.done)return;d.dataset.done=1;answered++;let i=Number(b.dataset.i);if(i===ans){score++;b.classList.add("correct");beep(true)}else{b.classList.add("wrong");d.querySelectorAll(".option")[ans].classList.add("correct");beep(false)}if(answered===u.quiz.length)finish()})});
function finish(){let st=state(),gained=score*10,stars=score===u.quiz.length?3:score>=Math.ceil(u.quiz.length/2)?2:1;updateStreak(st);st.xp+=gained;st.stars+=stars;st.quizzes++;st.best=Math.max(st.best,Math.round(score/u.quiz.length*100));if(!st.completed.includes(u.id))st.completed.push(u.id);st.quizHistory=(st.quizHistory||[]).filter(x=>x.unitId!==u.id);st.quizHistory.push({unitId:u.id,subject:id,title:u.title,score,total:u.quiz.length,percent:Math.round(score/u.quiz.length*100),date:today()});if(st.completed.length>=3&&!st.badges.includes("Penjelajah"))st.badges.push("Penjelajah");if(st.quizzes>=5&&!st.badges.includes("Rajin"))st.badges.push("Rajin");if(st.xp>=100&&!st.badges.includes("Bintang Muda"))st.badges.push("Bintang Muda");if(st.streak>=3&&!st.badges.includes("Konsisten"))st.badges.push("Konsisten");if(st.quizzes>=10&&!st.badges.includes("Juara Kuiz"))st.badges.push("Juara Kuiz");save(st);confetti();document.getElementById("result").innerHTML=`<div class="result"><div class="result-trophy">${score===u.quiz.length?'🏆':'🌟'}</div><h2>🎉 Tahniah, ${escapeHTML(st.name)}!</h2><p>Skor: <b>${score}/${u.quiz.length}</b> · ${Math.round(score/u.quiz.length*100)}%</p><p>+${gained} XP &nbsp; ${"⭐".repeat(stars)}</p><p>⚡ Level ${level(st.xp)} · 🔥 Streak ${st.streak} hari</p><p>${adaptiveMessage(score,u.quiz.length)}</p><div class="actions center"><a class="btn primary" href="game.html?subject=${id}&unit=${ui}">🎮 Main mini-game</a><a class="btn" href="lesson.html?subject=${id}">Unit lain</a><a class="btn" href="progress.html">Kemajuan</a></div></div>`}}
async function getTotalUnits(){let total=0;for(const sub of SUBJECTS){try{let d=await getSubject(sub.id);total+=d.units.length}catch(e){}}return total}
async function renderProgress(){let s=state(),total=await getTotalUnits(),pct=Math.min(100,Math.round(s.completed.length/total*100));document.getElementById("progress").innerHTML=`<div class="profile-strip"><div class="profile-avatar">${s.avatar}</div><div><h2>${escapeHTML(s.name)}</h2><div class="level-pill">⚡ Level ${level(s.xp)}</div><div class="level-track"><i style="width:${levelProgress(s.xp)}%"></i></div></div></div><div class="statgrid"><div class="stat"><b>⭐ ${s.stars}</b>Bintang</div><div class="stat"><b>⚡ ${s.xp}</b>XP</div><div class="stat"><b>🔥 ${s.streak}</b>Streak</div><div class="stat"><b>📝 ${s.quizzes}</b>Kuiz</div><div class="stat"><b>🎮 ${s.gameWins||0}</b>Game</div><div class="stat"><b>🏅 ${s.badges.length}</b>Badge</div></div><div class="card progress-main"><h2>📈 Kemajuan unit</h2><div class="bar"><i style="width:${pct}%"></i></div><p><b>${s.completed.length}</b> daripada <b>${total}</b> unit diselesaikan (${pct}%).</p><h2>🏆 Badge</h2><div class="badge-wall">${s.badges.length?s.badges.map(x=>`<span class="badge-item">🏅 ${escapeHTML(x)}</span>`).join(""):"<p>Belum ada badge. Teruskan belajar untuk mendapatkannya!</p>"}</div><div class="actions"><a class="btn primary" href="game.html">🎮 Main mini-game</a><a class="btn" href="profile.html">👤 Edit profil</a><button class="btn" onclick="resetProgress()">Reset kemajuan</button></div></div>`}
function beep(ok){try{let C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=ok?700:180;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(e){}}
function confetti(){for(let i=0;i<28;i++){let x=document.createElement("span");x.textContent=["⭐","🎉","✨","🌈","🎈"][i%5];x.style.cssText=`position:fixed;left:${Math.random()*100}vw;top:-30px;font-size:${18+Math.random()*18}px;z-index:9999;animation:fall ${1+Math.random()*1.5}s ease-out forwards;pointer-events:none`;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}}
function resetProgress(){if(confirm("Reset semua kemajuan dan profil?")){localStorage.removeItem(key);location.reload()}}
async function renderTeacher(){const root=document.getElementById('teacherDashboard');if(!root)return;const s=state(),total=await getTotalUnits(),history=s.quizHistory||[];const subjectData=[];for(const sub of SUBJECTS){try{const d=await getSubject(sub.id);const done=d.units.filter(u=>s.completed.includes(u.id)).length;const scores=history.filter(h=>h.subject===sub.id);const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b.percent,0)/scores.length):0;subjectData.push({...sub,total:d.units.length,done,avg});}catch(e){subjectData.push({...sub,total:0,done:0,avg:0})}}const needs=subjectData.filter(x=>x.avg>0&&x.avg<70);root.innerHTML=`<div class="teacher-head"><div><p class="eyebrow">👩‍🏫 Ruang Guru</p><h1>Teacher Dashboard</h1><p>Pantau pembelajaran murid pada peranti ini.</p></div><div class="teacher-actions"><button class="btn" onclick="window.print()">🖨️ Cetak</button><button class="btn primary" onclick="exportStudentReport()">⬇️ Simpan laporan</button></div></div><div class="teacher-profile card"><div class="teacher-avatar">${s.avatar}</div><div><h2>${escapeHTML(s.name)}</h2><p>Level ${level(s.xp)} · ${s.xp} XP · ${s.streak} hari streak</p></div></div><div class="statgrid teacher-stats"><div class="stat"><b>⭐ ${s.stars}</b>Bintang</div><div class="stat"><b>⚡ ${s.xp}</b>XP</div><div class="stat"><b>📝 ${s.quizzes}</b>Kuiz</div><div class="stat"><b>🎯 ${s.best}%</b>Skor terbaik</div><div class="stat"><b>🎮 ${s.gameWins||0}</b>Mini-game</div><div class="stat"><b>📚 ${s.completed.length}/${total}</b>Unit</div></div><section class="card teacher-section"><h2>📊 Kemajuan & purata skor subjek</h2><div class="subject-progress-list">${subjectData.map(x=>{let pct=x.total?Math.round(x.done/x.total*100):0;return `<div class="subject-row"><div class="subject-row-top"><span>${x.icon} <b>${x.name}</b></span><span>${x.done}/${x.total} unit · ${pct}% · ${x.avg||0}% purata</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('')}</div></section><section class="card teacher-section"><h2>🎯 Perlu perhatian</h2><p>${needs.length?needs.map(x=>`<span class="chip warning">${x.icon} ${x.name}: ${x.avg}%</span>`).join(' '):'🌟 Tiada subjek berisiko buat masa ini. Teruskan galakan!'}</p></section><section class="card teacher-section"><h2>📝 Rekod kuiz terkini</h2><div class="history-table">${history.slice(-8).reverse().map(h=>`<div><span>${escapeHTML(h.title)}</span><b>${h.score}/${h.total} (${h.percent}%)</b></div>`).join('')||'<p>Belum ada rekod kuiz.</p>'}</div></section><section class="card teacher-section teacher-note"><h3>ℹ️ Nota</h3><p>Data disimpan dalam browser/peranti semasa. Purata subjek dikira daripada cubaan kuiz yang direkodkan.</p></section>`}
function exportStudentReport(){const s=state();const report={platform:'TicerAinaaEdu Quest',student:s.name,avatar:s.avatar,level:level(s.xp),xp:s.xp,stars:s.stars,streak:s.streak,quizzes:s.quizzes,bestScore:s.best,gameWins:s.gameWins||0,badges:s.badges,completedUnits:s.completed,quizHistory:s.quizHistory||[],generatedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`laporan-${(s.name||'murid').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function escapeHTML(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initGame(){let p=new URLSearchParams(location.search),id=p.get('subject')||'math';let data=SUBJECTS.find(s=>s.id===id)||SUBJECTS[2];let title=document.getElementById('gameSubject');if(title)title.textContent=data.name;let prompt=document.getElementById('gamePrompt');let area=document.getElementById('gameArea');let scoreEl=document.getElementById('gameScore');let gameScore=0;function setScore(){if(scoreEl)scoreEl.textContent=gameScore}
window.startNumberGame=function(){let a=Math.floor(Math.random()*10)+1,b=Math.floor(Math.random()*10)+1,ans=a+b;area.innerHTML=`<div class="game-card"><div class="game-big">${a} ➕ ${b} = ?</div><div class="game-options">${[ans,ans+1,Math.max(0,ans-1),ans+2].sort(()=>Math.random()-.5).map(x=>`<button class="game-option" onclick="numberAnswer(this,${x},${ans})">${x}</button>`).join('')}</div></div>`;prompt.textContent='Pilih jawapan yang betul!'};
window.numberAnswer=function(btn,x,ans){if(x===ans){btn.classList.add('correct');gameScore++;beep(true);gameReward();}else{btn.classList.add('wrong');beep(false)}};
window.startMatchGame=function(){let words=id==='english'?['cat','dog','sun','book']:id==='math'?['circle','square','triangle','star']:id==='science'?['plant','magnet','water','earth']:['buku','rumah','kawan','keluarga'];let w=words[Math.floor(Math.random()*words.length)],scramble=w.split('').sort(()=>Math.random()-.5).join('');area.innerHTML=`<div class="game-card"><div class="game-big">${scramble}</div><p>Susun huruf menjadi perkataan:</p><input id="wordInput" class="game-input" autocomplete="off"><button class="btn primary" onclick="wordAnswer('${w}')">Semak ✓</button></div>`;prompt.textContent='Susun perkataan dengan betul!'};
window.wordAnswer=function(w){let v=(document.getElementById('wordInput').value||'').trim().toLowerCase();if(v===w){gameScore++;beep(true);gameReward();document.getElementById('gameArea').insertAdjacentHTML('beforeend','<p class="game-success">🎉 Betul!</p>')}else{beep(false);document.getElementById('gameArea').insertAdjacentHTML('beforeend','<p class="game-fail">Cuba lagi! 🌱</p>')}};
function gameReward(){let s=state();s.xp+=5;s.gameWins=(s.gameWins||0)+1;updateStreak(s);if(s.gameWins>=5&&!s.badges.includes('Pemain Hebat'))s.badges.push('Pemain Hebat');save(s);setScore();confetti()}
if(prompt)prompt.textContent='Pilih satu permainan untuk bermula.';setScore();document.querySelectorAll('.game-start').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.game-start').forEach(x=>x.classList.remove('active'));b.classList.add('active')}))}
