const SUBJECTS=[
{id:"bm",file:"bahasa-melayu.json",name:"Bahasa Melayu",icon:"📖",desc:"Membaca, menulis, bertutur dan memahami bahasa.",cls:"pink"},
{id:"english",file:"english-superminds.json",name:"English Year 1",icon:"🇬🇧",desc:"Learn English through simple, fun activities.",cls:"blue"},
{id:"math",file:"matematik.json",name:"Matematik",icon:"🔢",desc:"Nombor, operasi, bentuk dan penyelesaian masalah.",cls:"green"},
{id:"science",file:"sains.json",name:"Sains",icon:"🔬",desc:"Meneroka dunia dengan kemahiran saintifik.",cls:"orange"}];
const key="ticerAinaaEduQuestV4";
const avatars=["🧒","👧","🧑‍🎓","👦","👩‍🎓","🧒🏻","👧🏻","🧑🏻‍🏫"];
function state(){let d={xp:0,stars:0,badges:[],completed:[],quizzes:0,best:0,name:"Murid",avatar:"🧒",streak:0,lastDate:""};try{return {...d,...JSON.parse(localStorage.getItem(key)||"{}")} }catch(e){return d}}
function save(s){localStorage.setItem(key,JSON.stringify(s))}
function level(xp){return Math.floor(xp/100)+1}
function today(){return new Date().toISOString().slice(0,10)}
function updateStreak(st){let t=today();if(st.lastDate===t)return;let y=new Date();y.setDate(y.getDate()-1);let prev=y.toISOString().slice(0,10);st.streak=st.lastDate===prev?st.streak+1:1;st.lastDate=t}
function renderProfile(){let s=state();document.getElementById("studentName").value=s.name==="Murid"?"":s.name;document.getElementById("hello").textContent=s.name;document.getElementById("avatarBig").textContent=s.avatar;let g=document.getElementById("avatarGrid");g.innerHTML=avatars.map(a=>`<button type="button" class="avatar-choice ${a===s.avatar?'selected':''}" onclick="selectAvatar('${a}')">${a}</button>`).join("")}
function selectAvatar(a){let s=state();s.avatar=a;save(s);renderProfile()}
function saveProfile(){let s=state();s.name=(document.getElementById("studentName").value.trim()||"Murid").slice(0,30);save(s);document.getElementById("profileMsg").textContent="✅ Profil berjaya disimpan!";document.getElementById("hello").textContent=s.name}
async function getSubject(id){let x=SUBJECTS.find(a=>a.id===id);if(!x)throw new Error("Subjek tidak ditemui");const res=await fetch(x.file+"?v=40",{cache:"no-store"});if(!res.ok)throw new Error("Gagal memuat "+x.file);return await res.json()}
function renderSubjects(id){let el=document.getElementById(id);el.innerHTML=SUBJECTS.map(s=>`<article class="card"><div class="subject-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><a class="btn primary" href="lesson.html?subject=${s.id}">Buka subjek →</a></article>`).join("")}
function updateHomeStats(){let s=state();for(let k of ["stars","xp","badges"])document.getElementById(k).textContent=k==="badges"?s.badges.length:s[k];let n=document.getElementById("studentWelcome");if(n)n.textContent=s.name}
async function renderLesson(){let p=new URLSearchParams(location.search),id=p.get("subject")||"bm",data=await getSubject(id);document.title=data.name+" - TicerAinaaEdu Quest";document.getElementById("lesson").innerHTML=`<p class="eyebrow">${data.icon} ${data.name}</p><h1>Pilih unit</h1><p>${data.desc}</p><div class="grid">${data.units.map((u,i)=>`<article class="card unit"><div class="num">${i+1}</div><div><h3>${u.title}</h3><p>${u.learn}</p><ul class="points">${(u.points||[]).map(x=>`<li>${x}</li>`).join("")}</ul></div><a class="btn primary" href="quiz.html?subject=${id}&unit=${i}">Mula kuiz →</a></article>`).join("")}</div>`}
async function renderQuiz(){let p=new URLSearchParams(location.search),id=p.get("subject")||"bm",ui=Number(p.get("unit")||0),data=await getSubject(id),u=data.units[ui];if(!u){location.href="subjects.html";return}let root=document.getElementById("quiz"),score=0,answered=0;root.innerHTML=`<p class="eyebrow">${data.icon} ${data.name}</p><h1>${u.title}</h1><div class="lesson-box"><h3>💡 Apa kita belajar?</h3><p>${u.learn}</p><p><b>🎯 Aktiviti:</b> ${u.activity}</p></div><div id="questions"></div><div id="result"></div>`;let qbox=document.getElementById("questions");u.quiz.forEach((q,qi)=>{let [text,opts,ans]=q,d=document.createElement("div");d.className="quiz-q";d.innerHTML=`<h3>${qi+1}. ${text}</h3>`+opts.map((o,i)=>`<button class="option" data-i="${i}">${o}</button>`).join("");qbox.appendChild(d);d.querySelectorAll(".option").forEach(b=>b.onclick=()=>{if(d.dataset.done)return;d.dataset.done=1;answered++;let i=Number(b.dataset.i);if(i===ans){score++;b.classList.add("correct");beep(true)}else{b.classList.add("wrong");d.querySelectorAll(".option")[ans].classList.add("correct");beep(false)}if(answered===u.quiz.length)finish()})});function finish(){let st=state(),gained=score*10,stars=score===u.quiz.length?3:score>=Math.ceil(u.quiz.length/2)?2:1;updateStreak(st);st.xp+=gained;st.stars+=stars;st.quizzes++;st.best=Math.max(st.best,Math.round(score/u.quiz.length*100));if(!st.completed.includes(u.id))st.completed.push(u.id);if(st.completed.length>=3&&!st.badges.includes("Penjelajah"))st.badges.push("Penjelajah");if(st.quizzes>=5&&!st.badges.includes("Rajin"))st.badges.push("Rajin");if(st.xp>=100&&!st.badges.includes("Bintang Muda"))st.badges.push("Bintang Muda");if(st.streak>=3&&!st.badges.includes("Konsisten"))st.badges.push("Konsisten");save(st);confetti();document.getElementById("result").innerHTML=`<div class="result"><h2>🎉 Tahniah, ${st.name}!</h2><p>Skor: <b>${score}/${u.quiz.length}</b></p><p>+${gained} XP &nbsp; ${"⭐".repeat(stars)}</p><p>⚡ Level ${level(st.xp)} · 🔥 Streak ${st.streak} hari</p><a class="btn primary" href="lesson.html?subject=${id}">Unit seterusnya</a> <a class="btn" href="progress.html">Lihat kemajuan</a></div>`}}
async function getTotalUnits(){let total=0;for(const sub of SUBJECTS){try{let d=await getSubject(sub.id);total+=d.units.length}catch(e){}}return total}
async function renderProgress(){let s=state(),total=await getTotalUnits(),pct=Math.min(100,Math.round(s.completed.length/total*100));document.getElementById("progress").innerHTML=`<div class="statgrid"><div class="stat"><b>👤 ${s.avatar} ${s.name}</b>Profil</div><div class="stat"><b>🏅 Level ${level(s.xp)}</b>Level</div><div class="stat"><b>⭐ ${s.stars}</b>Bintang</div><div class="stat"><b>⚡ ${s.xp}</b>XP</div><div class="stat"><b>🔥 ${s.streak}</b>Streak</div><div class="stat"><b>📝 ${s.quizzes}</b>Kuiz</div></div><div class="card" style="margin-top:18px"><h2>📈 Kemajuan unit</h2><div class="bar"><i style="width:${pct}%"></i></div><p>${s.completed.length} daripada ${total} unit diselesaikan (${pct}%).</p><h2>🏆 Badge</h2><p>${s.badges.length?s.badges.map(x=>"🏅 "+x).join(" &nbsp; "):"Belum ada badge. Jawab kuiz untuk mendapatkannya!"}</p><a class="btn" href="profile.html">👤 Edit profil</a> <button class="btn" onclick="resetProgress()">Reset kemajuan</button></div>`}
function beep(ok){try{let C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?700:180;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(e){}}
function confetti(){for(let i=0;i<22;i++){let x=document.createElement("span");x.textContent=["⭐","🎉","✨","🌈"][i%4];x.style.cssText=`position:fixed;left:${Math.random()*100}vw;top:-30px;font-size:24px;z-index:9999;animation:fall ${1+Math.random()*1.5}s ease-out forwards`;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}}
function resetProgress(){if(confirm("Reset semua kemajuan dan profil?")){localStorage.removeItem(key);location.reload()}}

async function renderTeacher(){
  const root=document.getElementById('teacherDashboard'); if(!root)return;
  const s=state(); const total=await getTotalUnits();
  const subjectData=[];
  for(const sub of SUBJECTS){
    try{const d=await getSubject(sub.id); const done=d.units.filter(u=>s.completed.includes(u.id)).length; subjectData.push({...sub,total:d.units.length,done});}catch(e){subjectData.push({...sub,total:0,done:0});}
  }
  const avg= s.quizzes ? Math.round((s.best||0)) : 0;
  root.innerHTML=`
    <div class="teacher-head"><div><p class="eyebrow">👩‍🏫 Ruang Guru</p><h1>Dashboard Guru</h1><p>Pantau kemajuan pembelajaran murid pada peranti ini.</p></div><div class="teacher-actions"><button class="btn" onclick="window.print()">🖨️ Cetak laporan</button><button class="btn primary" onclick="exportStudentReport()">⬇️ Simpan laporan</button></div></div>
    <div class="teacher-profile card"><div class="teacher-avatar">${s.avatar}</div><div><h2>${escapeHTML(s.name)}</h2><p>Level ${level(s.xp)} · ${s.xp} XP · ${s.streak} hari streak</p></div></div>
    <div class="statgrid teacher-stats">
      <div class="stat"><b>⭐ ${s.stars}</b>Bintang</div><div class="stat"><b>⚡ ${s.xp}</b>XP</div><div class="stat"><b>📝 ${s.quizzes}</b>Kuiz</div><div class="stat"><b>🎯 ${avg}%</b>Skor terbaik</div><div class="stat"><b>🏅 ${s.badges.length}</b>Badge</div><div class="stat"><b>📚 ${s.completed.length}/${total}</b>Unit</div>
    </div>
    <section class="card teacher-section"><h2>📊 Kemajuan mengikut subjek</h2><div class="subject-progress-list">${subjectData.map(x=>{let pct=x.total?Math.round(x.done/x.total*100):0;return `<div class="subject-row"><div class="subject-row-top"><span>${x.icon} <b>${x.name}</b></span><span>${x.done}/${x.total} unit · ${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('')}</div></section>
    <section class="card teacher-section"><h2>🏆 Pencapaian</h2><p>${s.badges.length?s.badges.map(x=>`<span class="chip">🏅 ${escapeHTML(x)}</span>`).join(' '):'Belum ada badge.'}</p></section>
    <section class="card teacher-section teacher-note"><h3>ℹ️ Nota untuk guru</h3><p>Dashboard ini menggunakan data yang disimpan dalam <b>browser/peranti semasa</b>. Ia sesuai untuk semakan individu. Untuk mengumpul data ramai murid dari peranti berbeza, kita perlukan pangkalan data dan sistem log masuk pada versi akan datang.</p></section>`;
}
function escapeHTML(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function exportStudentReport(){
  const s=state(); const report={platform:'TicerAinaaEdu Quest',student:s.name,avatar:s.avatar,level:level(s.xp),xp:s.xp,stars:s.stars,streak:s.streak,quizzes:s.quizzes,bestScore:s.best,badges:s.badges,completedUnits:s.completed,generatedAt:new Date().toISOString()};
  const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`laporan-${(s.name||'murid').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`;a.click();URL.revokeObjectURL(a.href);
}
